### ISSUE TITLE
Does h5cpp work with libhdf5 1.10.5 ?

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#408]
Hi,

If anyone has tried to build h5cpp with libhdf5 1.10.5?

My college Vijay has tried to do it and he has got:

```h5cpp/src/h5cpp/file/direct_driver.cpp: In member function ‘virtual void hdf5::file::DirectDriver::operator()(const hdf5::property::FileAccessList&) const’:
h5cpp/src/h5cpp/file/direct_driver.cpp:80:48: error: invalid static_cast from type ‘const hdf5::property::FileAccessList’ to type ‘hid_t {aka long int}’
   if(H5Pset_fapl_direct(static_cast<hid_t>(fapl),alignment_,
                                                ^
make[2]: *** [src/h5cpp/CMakeFiles/h5cpp.dir/build.make:453: src/h5cpp/CMakeFiles/h5cpp.dir/file/direct_driver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:203: src/h5cpp/CMakeFiles/h5cpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2```

**Comment by eugenwintersberger** [comment]
Hi Jan. I just built h5cpp with libhdf5 1.10.4 on Debian Buster and the build works along with all tests.

**Comment by eugenwintersberger** [comment]
From what I see. The code which causes the failure is only built if the library was built with the direct driver enabled. This is, at least on Debian systems, usually not the case. Can you provide a bit more details about your colleges system configuration?

**Comment by jkotan** [comment]
He compile h5cpp on centos7.6 (on Maxwell) with modules for: g++ 6.3, libhdf5 1.10.5

**Comment by eugenwintersberger** [comment]
Can you try to figure out which flags where used when building the HDF5 library?

**Comment by jkotan** [comment]
To build hdf5/1.10.5 : 
```
./configure --with-szlib=/opt/hdf5/szip --enable-cxx --enable-java --enable-fortran2003 --enable-fortran --prefix=/opt/hdf5/hdf5-1.10.5
```
