### ISSUE TITLE
tests does not compile with libhdf5 < 1.10.1

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#593]
The tests does not compile with libhdf5 < 1.10.1 e.g. ubuntu18.04 i.e.
```
/build/h5cpp-0.5.0/test/property/file_creation_test.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____0()':
/build/h5cpp-0.5.0/test/property/file_creation_test.cpp:63:32: error: 'class hdf5::property::FileCreationList' has no member named 'page_size'
         REQUIRE_THROWS_AS(fcpl.page_size(), std::runtime_error);
                                ^
test/property/CMakeFiles/properties_test.dir/build.make:257: recipe for target 'test/property/CMakeFiles/properties_test.dir/file_creation_test.cpp.o' failed

```
