### ISSUE TITLE
speed read test does not compile on hdf5 1.8

### ISSUE THREAD

**Issue by jkotan** [ess-dmsc/h5cpp#383]
there is a stupid mistake which causes for hdf5 1.8
```
                                ^
[ 73%] Building CXX object test/CMakeFiles/unit_tests.dir/node/dataset_read_speed_test.cpp.o
/home/jkotan/sources/h5cpp/test/node/dataset_read_speed_test.cpp: In member function ‘virtual void DatasetReadSpeedTest::SetUp()’:
/home/jkotan/sources/h5cpp/test/node/dataset_read_speed_test.cpp:63:5: error: ‘dcpl’ was not declared in this scope
     dcpl.layout(property::DatasetLayout::CHUNKED);
     ^
/home/jkotan/sources/h5cpp/test/node/dataset_read_speed_test.cpp:68:18: error: ‘lcpl’ was not declared in this scope
            space,lcpl,dcpl,dapl);
                  ^
/home/jkotan/sources/h5cpp/test/node/dataset_read_speed_test.cpp:68:28: error: ‘dapl’ was not declared in this scope
            space,lcpl,dcpl,dapl);
```
I will create a fix.
