### ISSUE TITLE
Can't compile with boost 1.71

### ISSUE THREAD

**Issue by pdroalves** [ess-dmsc/h5cpp#443]
I'm running Ubuntu 20.04 and spent some time trying to compile h5cpp with my application without success. I was stuck in this error:

```
➜  build /usr/bin/c++  -Wall -Wextra -O3   CMakeFiles/logreg.dir/src/main.cpp.o  -o logreg  -L/usr/lib/x86_64-linux-gnu/hdf5/serial /usr/local/lib/libh5cpp.so -lpthread -lboost_system 
/usr/bin/ld: CMakeFiles/logreg.dir/src/main.cpp.o: in function `_GLOBAL__sub_I_main':
main.cpp:(.text.startup+0xdc): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: main.cpp:(.text.startup+0xe1): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: main.cpp:(.text.startup+0xe6): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status

```

I tried to replace the default boost installation, which is 1.71, by an older version, 1.67, and it worked like a charm. If this version dependency is real and not just something particular to my system, such information must be clear [here](https://github.com/ess-dmsc/h5cpp#how-to-build-h5cpp)

**Comment by eugenwintersberger** [comment]
The linker tells what's the problem. What remains is to figure out why it does not link with the appropriate boost::system library. Can you 
1. tell me which version of h5cpp you are using?
2. post a minimum CMakeList.txt file which can reproduce the problem?

**Comment by jkotan** [comment]
Hi @pdroalves,

have you tried to use our focal packages from HDRI repository
 
    https://ess-dmsc.github.io/h5cpp/users_guide/installing.html

and use them with cmake 

    https://ess-dmsc.github.io/h5cpp/users_guide/using.html
?

**Comment by pdroalves** [comment]
@eugenwintersberger sure!

1. I'm using [v0.3.3](https://github.com/ess-dmsc/h5cpp/releases/tag/v0.3.3)
2. I have this problem even when I try to compile the examples. Anyway, I think this is a minimum CMakeList.txt that may help:

```cmake
    PROJECT (myproject LANGUAGES CXX C)
    CMAKE_MINIMUM_REQUIRED(VERSION 3.11.0)

    SET(CMAKE_CXX_STANDARD 11)
    SET(CMAKE_CXX_STANDARD_REQUIRED ON)

    SET(CUDA_SEPARABLE_COMPILATION ON)

    find_package(h5cpp REQUIRED)

    INCLUDE_DIRECTORIES(
        include
        ${HDF5_INCLUDE_DIRS}
    )

    SET ( 
        libsrc 
        src/main.cpp
    )

    ADD_EXECUTABLE(foobar ${libsrc})

    TARGET_LINK_LIBRARIES(
        foobar
        h5cpp
    )
```

**Comment by pdroalves** [comment]
@jkotan Hello,
I just tried but looks like something is broken. I got this:

```
$ wget http://repos.pni-hdri.de/focal-pni-hdri.list
--2020-07-18 16:09:08--  http://repos.pni-hdri.de/focal-pni-hdri.list
Resolving repos.pni-hdri.de (repos.pni-hdri.de)... 131.169.180.46
Connecting to repos.pni-hdri.de (repos.pni-hdri.de)|131.169.180.46|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-18 16:09:08 ERROR 404: Not Found.
```

**Comment by jkotan** [comment]
Sorry, I forgot to add the file for focal. Now, 

    wget http://repos.pni-hdri.de/focal-pni-hdri.list

 should work.

**Comment by yuelongyu** [comment]
Checked my ubuntu 20.04, boost 1.71.0. It seems those symbols are not exported.

```
$ readelf -Ws /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0

Symbol table '.dynsym' contains 6 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __cxa_finalize
     2: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     4: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
     5: 0000000000001100     5 FUNC    GLOBAL DEFAULT   10 _ZN5boost6system23dummy_exported_functionEv
```
looking at the source code, the methods are still there. 
https://github.com/boostorg/system/blob/boost-1.71.0/include/boost/system/error_code.hpp
So possibly the boost 1.71.0 on ubuntu 20.04 is built with some flags which makes those symbols invisible.

**Comment by eugenwintersberger** [comment]
The preprocessor variable responsible seems to be `BOOST_SYMBOL_VISIBLE`. I have no idea yet where this one is defined yet. It is either somewhere automatically by the Boost build system or in the Debian build script. Both symbols are present for Boost::system 1.67.0 on Debian 10.

**Comment by jkotan** [comment]
Weird, I've tried the example https://ess-dmsc.github.io/h5cpp/users_guide/using.html on my ubuntu 20.04

     sudo apt-get update
     sudo apt-get dist-upgrade
     sudo apt-get install libh5cpp0.3.3-dev libhdf5-dev

and it works fine:

```
jkotan@dellek:~/h5cpp_test/build$ cmake -Dh5cpp_DIR=/tmp/lib/cmake/h5cpp-0.3.3 ../
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable exact version "1.10.4") found components: C 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jkotan/h5cpp_test/build
jkotan@dellek:~/h5cpp_test/build$ make
Scanning dependencies of target h5cpp_test
[ 50%] Building CXX object CMakeFiles/h5cpp_test.dir/main.cpp.o
[100%] Linking CXX executable h5cpp_test
[100%] Built target h5cpp_test
jkotan@dellek:~/h5cpp_test/build$ ./h5cpp_test 
INTEGER
jkotan@dellek:~/h5cpp
```
Have I missed something?

**Comment by yuelongyu** [comment]
maybe this example is simple enough so that system_category/generic_category is not directly/indirectly used here, that's why the linker doesn't care if these two symbols are marked as undefined.

**Comment by jkotan** [comment]
I've also compiled python binding for h5cpp without any problem but may they are also too simple. :)

**Comment by yuelongyu** [comment]
checked the changes of boost.system, from 1.69 it's header only library. So it's reasonable there is no symbol in the so file. I don't see any place in h5cpp is directly using these two methods. In boost.filesystem 1.71.0 so file, the generic_category is marked as undefined, I guess that's the problem, this symbol doesn't exist in any so file in boost 1.71.0.  Don't know why, in principle, this shouldn't happen.

**Comment by eugenwintersberger** [comment]
I can confirm Jans' results. I built the examples on an Ubuntu 20.04 installation without any troubles. 
```bash
$ objdump -CT append_scalar_data | grep boost::system::generic_category
0000000000027190 u    DO .bss	0000000000000008  Base        guard variable for boost::system::generic_category()::generic_category_instance
0000000000027180 u    DO .bss	0000000000000010  Base        boost::system::generic_category()::generic_category_instance
0000000000015e2f  w   DF .text	000000000000004e  Base        boost::system::generic_category()
```
Indeed the missing symbols show up in the resulting binaries. This is getting mysterious. In particular, since the compile commands in the Makefile show no uncommon options and flags.

**Comment by yuelongyu** [comment]
Just double checked the UND methods in boost.filesystem 1.71.0. The symbol missing is from standard library, not from boost itself, sorry, my fault.
```
FUNC    GLOBAL DEFAULT  UND _ZNSt3_V216generic_categoryEv@GLIBCXX_3.4.21
```
I've also tried to compile all the h5cpp, its examples and my own application with boost 1.71, everything works without problem.

**Comment by eugenwintersberger** [comment]
@pdroalves On which OS are you building the code?

**Comment by pdroalves** [comment]
@eugenwintersberger I'm building on machines running Ubuntu 20.04 with the latest updates.

**Comment by eugenwintersberger** [comment]
@pdroalves This is really strange as  I am using an Ubuntu 20.4 installation too. Slowly I am really running out of ideas what is going wrong here.

**Comment by pdroalves** [comment]
Maybe gcc's version? I'm running gcc 7.5.0.

**Comment by jkotan** [comment]
Yes. That  may explain the problem. Have you try to use standard ubuntu g++ version, i.e. 9.3 ?

**Comment by jkotan** [comment]
Using 7.5 on ubuntu 20.04 to avoid linker errors you need to compile everything from scratch, i.e. libhdf5, libboost, libh5cpp and all other c++ libraries you use.

**Comment by jkotan** [comment]
I think it can be close
